# Generated by Django 5.2.4 on 2025-08-14 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='plan_name',
            field=models.CharField(blank=True, choices=[('monthly', '1 Month'), ('yearly', '1 Year')], max_length=20),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.product'),
        ),
    ]
