# Generated by Django 5.2.4 on 2025-08-14 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_subscription_plan_name_alter_subscription_plan'),
    ]

    operations = [
    ]
