# Generated by Django 5.2.4 on 2025-08-25 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_auto_20250814_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='recurring_interval',
            field=models.CharField(choices=[('month', 'Monthly'), ('year', 'Yearly'), ('weekly', 'Weekly'), ('', 'One-time')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='plan_name',
            field=models.CharField(blank=True, choices=[('weekly', '1 Week'), ('monthly', '1 Month'), ('yearly', '1 Year')], max_length=20),
        ),
    ]
