# Generated by Django 5.2.4 on 2025-08-14 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='free_comment_used',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='has_active_subscription',
            field=models.BooleanField(default=False),
        ),
    ]
