# Generated by Django 5.2.4 on 2025-08-14 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_free_comment_used_user_has_active_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='subscription_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='subscription_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
