# Generated by Django 5.2.4 on 2025-08-19 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_subscription_end_user_subscription_start'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='has_active_subscription',
        ),
    ]
