# Generated by Django 5.2.4 on 2025-08-27 07:17

import blog.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=blog.utils.user_directory_path),
        ),
    ]
